### ISSUE TITLE
Roadmap to dual optimizer

### ISSUE THREAD

**Issue by guilhermebodin** [guilhermebodin/Dualization.jl#16]
Layers:
1) full_bridge_optimizer (to perform necessary conversions)
2) CachingOptimizer (to hold modified Primal model data)
3) UniversalFallback (to deal with attributes)
4) DualOptimizer (is a solver that depends on a solver, like Pajarito)
5) A dual_backend which can be: Solver (like GLPK or SCS) OR a cache to hold Dual model (DualizableModel)

DualOptimizer will define supports functions in the following way:
will receive something to check, will obtain what it is converted to (in dualization) will test if the dual_backend supports the converted constraint type

a) DualOptimizer(solver = GLPK.Optimizer()) passes the dual strainght to the solver
b) DualOptimizer() or DualOptimizer(solver = DualizableModel{Float64}()) holds the dual model data in the dualizable model

**Comment by blegat** [comment]
What does 1. to 5. represent ? The order of the layer ? You cannot use a linear order since DualOptimizer and CachingOptimizer have two underlying model : the cache and the optimizer.
I would not expect CachingOptimizer to be needed by DualOptimizer. And we should certainly not use the UniversalFallback on top of DualOptimizer as it won't pass the info through. The UF should be used by the cache of DualOptimizer
